version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
       - make install
  package:
    commands:
       - make package
  publish:
    commands:
       - make publish